ALTER TABLE "trades" ADD COLUMN "asset_class" TEXT NOT NULL DEFAULT 'Stock';
ALTER TABLE "trades" ADD COLUMN "exit_date" DATETIME;
ALTER TABLE "trades" ADD COLUMN "fees" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "trades" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'OPEN';
